### ISSUE TITLE
[BUG] Error when closing and reopening app

### ISSUE THREAD

**Issue by SaadArdati** [bsutton/sounds#22]
## Sounds Version : 

1.0.0-beta.5

--------------------------------------------------------

## Severity

Error

--------------------------------------------------------

## Platforms you faced the error 

Android Pixel 4a emulator running Android R+

--------------------------------------------------------

## Logs
```
I/flutter (10958): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter (10958): The following NoSuchMethodError was thrown during a platform message callback:
I/flutter (10958): The getter 'name' was called on null.
I/flutter (10958): Receiver: null
I/flutter (10958): Tried calling: name
I/flutter (10958): 
I/flutter (10958): When the exception was thrown, this was the stack:
I/flutter (10958): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (10958): #1      Audio.toString (package:sounds_common/src/media_format/audio.dart:312:44)
I/flutter (10958): #2      _StringBase._interpolate (dart:core-patch/string_patch.dart:848:19)
I/flutter (10958): #3      Track.toString (package:sounds_common/src/track.dart:49:59)
I/flutter (10958): #4      _StringBase._interpolate (dart:core-patch/string_patch.dart:848:19)
I/flutter (10958): #5      SoundPlayer._onSystemAppResumed (package:sounds/src/sound_player.dart:549:14)
I/flutter (10958): #6      onSystemAppResumed (package:sounds/src/sound_player.dart:883:55)
I/flutter (10958): #7      PlayerBasePlugin.onSystemAppResumed.<anonymous closure> (package:sounds/src/plugins/player_base_plugin.dart:281:7)
I/flutter (10958): #8      BasePlugin.forEachSlot (package:sounds/src/plugins/base_plugin.dart:173:15)
I/flutter (10958): #9      PlayerBasePlugin.onSystemAppResumed (package:sounds/src/plugins/player_base_plugin.dart:277:5)
I/flutter (10958): #10     BasePlugin.didChangeAppLifecycleState (package:sounds/src/plugins/base_plugin.dart:69:9)
I/flutter (10958): #11     WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:671:16)
I/flutter (10958): #12     ServicesBinding._handleLifecycleMessage (package:flutter/src/services/binding.dart:190:5)
I/flutter (10958): #13     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:49)
I/flutter (10958): #14     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:260:33)
I/flutter (10958): <asynchronous suspension>
I/flutter (10958): #15     _invoke3.<anonymous closure> (dart:ui/hooks.dart:282:15)
I/flutter (10958): #19     _invoke3 (dart:ui/hooks.dart:281:10)
I/flutter (10958): #20     _dispatchPlatformMessage (dart:ui/hooks.dart:156:5)
I/flutter (10958): (elided 3 frames from dart:async)
I/flutter (10958): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

-----------------------------------------------------

**To Reproduce**
1. App is open and playing audio
2. Press the home button
3. Reopen app
4. Error is thrown in the console immediately. but the audio plays normally.

**Comment by relf108** [comment]
Fixed in 1.0.0-beta.6
After resuming, track was not in correct state due to incorrect release method.
